# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dataframe_analyzer.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'dataframe_analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64\x61taframe_analyzer.proto\x12\x12\x64\x61taframe_analyzer\"C\n\x17\x41nalyzeDataframeRequest\x12\x11\n\tdataframe\x18\x01 \x01(\t\x12\x15\n\ruser_question\x18\x02 \x01(\t\":\n\x18\x41nalyzeDataframeResponse\x12\x10\n\x08\x64\x61tatype\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2z\n\x10\x41nalyzeDataframe\x12\x66\n\tGetAnswer\x12+.dataframe_analyzer.AnalyzeDataframeRequest\x1a,.dataframe_analyzer.AnalyzeDataframeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataframe_analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEDATAFRAMEREQUEST']._serialized_start=48
  _globals['_ANALYZEDATAFRAMEREQUEST']._serialized_end=115
  _globals['_ANALYZEDATAFRAMERESPONSE']._serialized_start=117
  _globals['_ANALYZEDATAFRAMERESPONSE']._serialized_end=175
  _globals['_ANALYZEDATAFRAME']._serialized_start=177
  _globals['_ANALYZEDATAFRAME']._serialized_end=299
# @@protoc_insertion_point(module_scope)
